### ISSUE TITLE
[Feature] admiralty-file-input - Implement validation

### ISSUE THREAD

**Issue by developernm** [UKHO/admiralty-design-system#119]
Implement validation for the file input.

The scenario we are trying to complete is where specific file type(s) are prevented from being selected or allowed to be selected but an error appears

```html
          <admiralty-file-input id="file-input" multiple label="Select file or drag it here" (fileInputChange)="populateFiles($event)"></admiralty-file-input>
```

![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/6fedce0d-bbce-44a5-87f9-cfbe629d0535)

**Comment by UKHOGreg** [comment]
Missed the dashed red outline on the input
