### ISSUE TITLE
[BUG] admiralty-button doesn't copy attributes

### ISSUE THREAD

**Issue by osric-ukho** [UKHO/admiralty-design-system#141]
**Describe the bug**

`<admiralty-button>` doesn't copy `name` or `value` attributes, breaking buttons

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `<admiralty-button name="test" value="hello">Hello</admiralty-button>` to a page

**Expected behaviour**
The generated button to include the name and value, so that when the parent form submits it includes the name/value in the payload

**Additional context**
Dealbreaking bug

**Comment by KatiePUX** [comment]
review by KP and GW - needs further review with @ecstaticrainbow

**Comment by KatiePUX** [comment]
KP liaised with team Kai - this is creating a bug for every single page of the service
