### ISSUE TITLE
SPIKE: Test Web Components package with CMS's / frameworks

### ISSUE THREAD

**Issue by UXdave-alexander** [UKHO/admiralty-design-system#148]
Investigate functionality of Design System with CMS's used internally such as:

- Sharepoint
- Atlassian
- Bootstrap
- Power BI
- Suggestions for new Intranet TBC

**Comment by KatiePUX** [comment]
We know it works on Atlassian status page need to find out about others 
Add Power Apps to the list also

**Comment by KatiePUX** [comment]
Documentation page on the website to say - if you need to integrate to this website 'do this'
Should come after CSS ticket
Testing how strong is our CSS file

**Comment by KatiePUX** [comment]
Discussed as a team and decided not required at this stage.
