### ISSUE TITLE
Create modal pop up including greyed out background

### ISSUE THREAD

**Issue by UXdave-alexander** [UKHO/admiralty-design-system#162]
**Is your feature request related to a problem? Please describe.**
This new component is needed for Data Upload and as a component to prevent user error

**Describe the solution you'd like**
<img width="458" alt="image" src="https://github.com/UKHO/admiralty-design-system/assets/60921243/f0557897-0aa1-4910-8eeb-5d71a2b1ec93">
<img width="146" alt="image" src="https://github.com/UKHO/admiralty-design-system/assets/60921243/6d14ac2c-367f-4051-a27a-fad08546c5ce">
Images show desktop and mobile to include breakpoint at tablet. Background is #333333 with 65% capacity. 

**Describe alternatives you've considered**
Thoroughly checked and designed so no alterntives

**Additional context**
As above
See Katie Paige as Designer

**Comment by UKHOGreg** [comment]
Talked with @ecstaticrainbow 

Plan is:
- prop for the heading text (don't use h elements)
- component with two named slots
  - One for the content
  - One for the action buttons

**Comment by UKHOGreg** [comment]
WIP

![image](https://github.com/UKHO/admiralty-design-system/assets/51328760/03cae23f-a4e8-41a3-b1eb-8f742df183c8)

**Comment by UKHOGreg** [comment]
Latest WIP:

![image](https://github.com/UKHO/admiralty-design-system/assets/51328760/84aa2fc1-91e6-48ed-9261-a3b79e60ae47)

**Comment by UKHOGreg** [comment]
Chat with @ecstaticrainbow 

- Can use media queries/breakpoints to determine size of the modal, but could google for a better solution.
- Escape key to close modal?

**Comment by UKHOGreg** [comment]
Agreed with @KatiePUX to make responsiveness out of scope due to technical difficulties with implementing it (the issue being incorrect CSS being generated from SCSS)

**Comment by UKHOGreg** [comment]
Agreed with @KatiePUX to make a correctly functioning doc website page out of scope .

Currently the modal dialog hijacks the page.
