### ISSUE TITLE
[BUG] Heading structure has been organised in a way that causes confusion for screen reader users.

### ISSUE THREAD

**Issue by KatiePUX** [UKHO/admiralty-design-system#184]
Heading structure has been organised in a way that causes confusion for screen reader users.

Reference:
Usability
Issue ID: DAC_Heading_Structure_Usability_01
URL: https://ukhodataupload.admiralty.co.uk/external/intellectual-property
Page: Intellectual property and Data Sharing
Journey:1.6

Headings have been ordered in a way that causes confusion for screen reader users. This 
instance can be found with the ‘contact details (optional)’ heading below ‘additional 
contacts’. Heading structure has been organised in a way that ‘additional contacts’ is a 
heading level 2, and the following ‘contact details (optional)’ heading is a level 6; for screen 
reader users, a skipped heading level implies content has been missed, which is not the 
case.

**Comment by KatiePUX** [comment]
Outcome of DAC Accessibility Report - for more information view: 

[https://ukho.sharepoint.com/sites/EXT_Data_Upload/Shared%20Documents/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1711376954679&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yNDAyMjkyMDYwMiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fsites%2FEXT%5FData%5FUpload%2FShared%20Documents%2FGeneral%2FAccessibility%20Audit%2FPrivate%20Beta%2FDAC%20Accessibility%20Report%20WCAG%202%2E2%20UKHO%20UDU%20130324%20Final%20Version%2Epdf&viewid=8b1f0a9e%2D2897%2D4a4d%2D8283%2Dcc660e97e3e4&parent=%2Fsites%2FEXT%5FData%5FUpload%2FShared%20Documents%2FGeneral%2FAccessibility%20Audit%2FPrivate%20Beta](url)

Page 58-60

**Comment by KatiePUX** [comment]
Tickets 114, 157, 178, 149 linked - let team Kai know when you are working on these so they can make adjustments when required

**Comment by buzzub** [comment]
This ticket refers to how the `https://ukhodataupload.admiralty.co.uk/external/intellectual-property` page has been created and is not something that can directly be affected by the Design System.

The contact details section of `https://ukhodataupload.admiralty.co.uk/external/intellectual-property` is using a `<h2>` tag followed by a `<h6>` tag.

This needs updating so that it is a `<h2>` tag followed by a `<h3>` tag.

**Comment by buzzub** [comment]
Need to communicate this to team Kai

**Comment by KatiePUX** [comment]
Naran has communicated this to Proteus - closing
