### ISSUE TITLE
[BUG] ARC Tool issue - Focusable Element Found Within Presentational Children

### ISSUE THREAD

**Issue by Satyam15302** [UKHO/admiralty-design-system#213]
## Describe the bug

A focusable element is found within an ARIA role that defines its children as presentational. This contradicts the intended use of ARIA roles and affects accessibility.

## To Reproduce

1. Open the web application.

2. Navigate to the "Confirm exchange set content" page.

3. Use a web accessibility testing tool (e.g., ARC Toolkit).

4. Observe the error regarding focusable elements within presentational children.

## Expected behavior

Focusable elements should not be children of elements with presentational roles or should be adjusted to maintain proper accessibility semantics.

## Screenshots

![Focusable element found ](https://github.com/UKHO/admiralty-design-system/assets/108277912/0d9ab009-3998-4a31-a7b8-08f2131f9131)

## Additional context

This issue affects checkboxes used in the "Confirm exchange set content" page. Each checkbox is within a `div` with presentational roles, which conflicts with their focusable nature.

**Comment by KatiePUX** [comment]
We would need to remove the role = check box from the div

**Comment by developernm** [comment]
[PR - fix](https://github.com/UKHO/admiralty-design-system/pull/269)
