### ISSUE TITLE
[BUG] admiralty-header breaks when updating headerItems once loaded

### ISSUE THREAD

**Issue by developernm** [UKHO/admiralty-design-system#222]
When you try to update the headerItems, it breaks the header styling completely. After showing @ecstaticrainbow we noticed it was introduced in v13 somewhere, but the latest version ```0.14.1--canary.197.a2482c6.0``` still has the issue.

![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/07c13622-7220-45a8-853b-9893199a633f)

```html
<admiralty-header alt="UK Hydrographic Office"
                  (titledClicked)="dashboardNavigate()"
                  [logoImgUrl]="header.logoImgUrl"
                  [logoLinkUrl]="header.logoLinkUrl"
                  [logoAltText]="header.logoAltText"
                  [headerTitle]="header.title">
  <ng-container *ngFor="let item of headerItems">
    <admiralty-header-menu-item [menuTitle]="item.title"
                                (menuItemClick)="navigate(item.routerLink)"
                                slot="items"></admiralty-header-menu-item>
  </ng-container>
</admiralty-header>

<admiralty-button (click)="this.updateHeaderItems()">update header items</admiralty-button>

```

```ts
  public headerItems: HeaderItem[] = [];

  public header: any = {
    title: 'Data Upload',
    logoImgUrl: '../assets/UKHO_linear_logo.svg',
    logoLinkUrl: 'https://www.admiralty.co.uk/',
    logoAltText: 'UK Hydrographic Office',
    authOptions: {
      isSignedIn: () => this.isLoggedIn(),
      signInHandler: () => this.login(),
      signedInButtonText: 'Account',
      signOutHandler: () => this.logout(),
      userProfileHandler: () => this.authenticationService.editProfile()
    }
  };

  public updateHeaderItems(): void {
    this.headerItems = [
      {
        title: 'Surveys',
        clickAction: () => router.navigate(['./internal/surveys']),
        navActive: false,
        routerLink: './internal/surveys'
      }
    ];
  }
```

When you look into the html, it gets applied in a completely different place for some strange reason. 

Correct HTML - admiralty-menu-header-item is in the correct position
![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/5660dbb2-cc02-497e-812f-bb4a5049613c)

Incorrect HTML - admiralty-menu-header-item is in the incorrect position
![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/6bedb481-1984-4460-842b-285c808a62cb)

**Comment by KatiePUX** [comment]
@ecstaticrainbow shall I move this one to 'in progress' and assign to you

**Comment by ecstaticrainbow** [comment]
I'll do it, thanks for bringing to my attention
