### ISSUE TITLE
[BUG] Use of SCSS Variables, Mixins etc

### ISSUE THREAD

**Issue by developernm** [UKHO/admiralty-design-system#34]
**Describe the bug**
I cannot import colours variables as you could from the previous design system.

**To Reproduce**
1. Install the library

You cannot find any SCSS files within the package to import variables and mixins into the main project

**Expected behavior**
I should be able to do something like the below but for this library:

@use '~@ukho/design-system/styles/base/typography';
@use '~@ukho/design-system/styles/base/colours';

**Comment by buzzub** [comment]
Fixed by #165
