### ISSUE TITLE
[BUG] admiralty-type-ahead-item fails to append "value" on dynamic data regardless of whether its set locally or from an API

### ISSUE THREAD

**Issue by developernm** [UKHO/admiralty-design-system#50]
Whenever i try to render dynamic data whether it be an array of type set locally or fetching data from an API to then render using observables, the admiralty-type-ahead-item fails to append the value

```html
<admiralty-type-ahead resultsOnInitFocus="true"
                                      type="text"
                                      [label]="'Commissioning organisation *'">
  <ng-container *ngFor="let item of commissioningOrganisations$ | async" >
    <admiralty-type-ahead-item [value]="item.organisationName"></admiralty-type-ahead-item>
  </ng-container>
</admiralty-type-ahead>
```
```ts
commissioningOrganisations$: Observable<CommissioningOrganisation[]>;

export interface CommissioningOrganisation {
  id?: number;
  organisationName?: string;
}
```

![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/ecc43fca-894e-4d8e-aff0-4b498241a48a)

**Comment by developernm** [comment]
@LukeTaylor34 @liamfarley13 FYI

**Comment by UKHOGreg** [comment]
Hard-coded vs for each generated:

![image](https://github.com/UKHO/admiralty-design-system/assets/51328760/7097bf04-73c3-4fc3-9646-08dd67adfb95)

**Comment by UKHOGreg** [comment]
Tried changing `value` prop to `thevalue` in the `admiralty-type-ahead-item` and had exactly the same result.

**Comment by UKHOGreg** [comment]
Attempted upgrade of:
`"@stencil/angular-output-target": "^0.7.1",`
made no difference.
