### ISSUE TITLE
[BUG] Web Components need to implement ControlValueAccessor in order to use angular formControl functions

### ISSUE THREAD

**Issue by developernm** [UKHO/admiralty-design-system#51]
**Describe the bug**
Cannot use formControl functions on the web components, in particular formControlName or formControlArray on most of the web components. Currently it displays the error attached. 

![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/8796afee-ce22-49e9-85ee-20a432826d57)

```
<admiralty-select formControlName="purpose"
                            [hint]="'This helps us understand where to focus when processing your data'"
                            [label]="'Primary purpose of data collection *'">
    <option disabled></option>
    <ng-container *ngFor="let item of purposes">
      <option>{{item.purpose}}</option>
    </ng-container>
</admiralty-select>
```

**Comment by developernm** [comment]
@LukeTaylor34 @liamfarley13

**Comment by developernm** [comment]
TextArea and Radio / Radio-Group, are not recalling the value from using the formControlName, whereas the other components do. FYI @ecstaticrainbow

**Comment by UKHOGreg** [comment]
TB still needs to do the typeahead

**Comment by KatiePUX** [comment]
Spoke with Naran, this is still valid. Class needs to be added to added to radio, radio group and text area. Katie move across to approved.

**Comment by developernm** [comment]
Waiting for confirmation on whether autocomplete has replaced typeahead, which makes the work for the typeahead, redundant. 

UDU currently use radio, radio group, autocomplete and text-area components with form controls without an issue.

**Comment by developernm** [comment]
Closing this ticket as all is complete and typeahead is being removed as part of this [ticket](https://github.com/UKHO/admiralty-design-system/issues/290) and [pull request](https://github.com/UKHO/admiralty-design-system/pull/292)
