### ISSUE TITLE
[BUG] admiralty-select & admiralty-input styling alignment 

### ISSUE THREAD

**Issue by developernm** [UKHO/admiralty-design-system#88]
Place the two components side by side and you can see the styling differences. Can this be aligned correctly please?

```html
          <div style="display: flex">
            <admiralty-select style="margin-right: 10px; width: 250px"
                              [label]="'Vertical datum *'">
              <option disabled></option>
              <option>test</option>
              <option>test 2</option>
            </admiralty-select>
            <admiralty-input style="margin-right: 10px; width: 250px"
                             [label]="'Please give further details:'"></admiralty-input>
          </div>
```

![image](https://github.com/UKHO/admiralty-design-system/assets/24655342/1048bfe9-6398-4776-bfda-e67275ca9c82)

**Comment by UKHOGreg** [comment]
The issue appears to be that the `<admiralty-hint>` element is causing this.

**Comment by UKHOGreg** [comment]
![image](https://github.com/UKHO/admiralty-design-system/assets/51328760/6e7cefed-baa0-4bd0-b9b7-a7168a7d8bb0)
after conditionally removing the hint from the select
